# Generated by Django 4.2.2 on 2023-06-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlab',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gitlab',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gitlab',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
